### PR TITLE
[dpdk] Emit table config data in txt format from const entries

### PR DESCRIPTION
**Pull request by kamleshbhalui**
It has been verified by Kannan. it's for upstream same patch.

### CODE REVIEW

**Review by maheswari-s — APPROVED** [review]
Looks fine

**Review by psivanup — APPROVED** [review]
Looks fine.
Please check if any test shall be added for the changes made.

**Review by syogender — COMMENTED** [review]
no test case and output to check/ verify?

**Review by usha1830 — APPROVED** [review]
Looks fine

**Comment by usha1830** [comment]
> > no test case and output to check/ verify?
> 
> I do not have issue adding a testcase, but upstream maintainer says no new reference file. @usha1830 please confirm
We can give it a try. For context json reference output, we were asked to remove it from the repository.

**Comment by kamleshbhalui** [comment]
Here is table config for added test, it's hard to add it to test and verify as file name is derived from actual table name in spec file and there can be many of them
```
match 0x1 0x1/0xF priority 0x4 action a_with_control_params x 0x1 
match 0x2 0x1181/0xFFFF priority 0x3 action a_with_control_params x 0x2 
match 0x3 0x1000/0xF000 priority 0x2 action a_with_control_params x 0x3 
match 0x4 0x0/0x0 priority 0x1 action a_with_control_params x 0x4 
```

**Comment by usha1830** [comment]
> Here is table config for added test, it's hard to add it to test and verify as file name is derived from actual table name in spec file and there can be many of them

Agree. Adding this to test would need some additional scripts to fetch table names from the spec file and then creating DPDK CLI file with those table names

**Comment by usha1830** [comment]
> Here is table config for added test, it's hard to add it to test and verify as file name is derived from actual table name in spec file and there can be many of them
> 
> ```
> match 0x1 0x1/0xF priority 0x4 action a_with_control_params x 0x1 
> match 0x2 0x1181/0xFFFF priority 0x3 action a_with_control_params x 0x2 
> match 0x3 0x1000/0xF000 priority 0x2 action a_with_control_params x 0x3 
> match 0x4 0x0/0x0 priority 0x1 action a_with_control_params x 0x4 
> ```

@kamleshbhalui  please attach the test for which you have this 

> Here is table config for added test, it's hard to add it to test and verify as file name is derived from actual table name in spec file and there can be many of them
> 
> ```
> match 0x1 0x1/0xF priority 0x4 action a_with_control_params x 0x1 
> match 0x2 0x1181/0xFFFF priority 0x3 action a_with_control_params x 0x2 
> match 0x3 0x1000/0xF000 priority 0x2 action a_with_control_params x 0x3 
> match 0x4 0x0/0x0 priority 0x1 action a_with_control_params x 0x4 
> ```

Other output files not added for the test? .spec, frontend.p4 ,midend.p4 etc are missing

**Pull request closed without merging**
